### ISSUE TITLE
Feature request - HA turn_off behavior

### ISSUE THREAD

**Issue by 0rn0lf** [fbradyirl/openwebifpy#10]
With the new integration to Home Assistant its not necessary to deal with custom components anymore.

This is a feature request for a new parameter to control which PowerState the "turn_off" service call will call via openwebif.
It shouldnt be too hard to implement and could look like this:
```
turn_off_behavior:
  - standby (default)
  - deep_standby
  - shutdown
```

Current situation is that the box will drain around 30W energy even in standby. This is because its always listening for incoming streaming requests. 
With the new option it would be possible to completely turn off the box and on again with a simple automation. 
Because most of the VU+ boxes dont have wake-on-lan you could use a smart power plug to power on the box again. This should use around 5W and you dont have to worry about your HDD because it was stopped before the power was killed.

**Comment by fbradyirl** [comment]
I am working on this. FYI here is the exception when the box is off. I will reduce error logging when in deep standby.

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='<IP Redacted>', port=80): Max retries exceeded with url: /api/statusinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x6e563210>: Failed to establish a new connection: [Errno 113] Host is unreachable'))


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x6e6d5310>: Failed to establish a new connection: [Errno 113] Host is unreachable
```
